### ISSUE TITLE
is user signup supports ?

### ISSUE THREAD

**Issue by santoshgistto** [benwinding/react-admin-firebase-demo#1]
is user signup supports ?

**Comment by benwinding** [comment]
It hasn't been implemented, but could be added in the future. 

Just curious, what are you using this for? Not sure if it's a common use case for `react-admin`

**Comment by santoshgistto** [comment]
thanks @benwinding. Yes for react-admin use case we need to register the user before showing the dashboard

**Comment by benwinding** [comment]
FYI, this was implemented in the demo app within the main `react-admin-firebase` repository. Basically now we can use the [firebase-ui-web](https://github.com/firebase/firebaseui-web) library, which lets us have signups from Google, Facebook etc..

![image](https://user-images.githubusercontent.com/11782590/77244901-3fbe7100-6c6a-11ea-82bc-2093aadd5b10.png)

The way it's implemented is demonstrated in [this file.](https://github.com/benwinding/react-admin-firebase/blob/623bc6ac4cb87812e83d9edc02ed8381d0d111b7/src-demo/src/CustomLoginPage.js)

Cheers,
Ben
