### ISSUE TITLE
'BROWSER' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by e-labInnovations** [benwinding/react-admin-firebase-demo#11]
![image](https://user-images.githubusercontent.com/33958126/85405377-f68a0000-b57d-11ea-82c4-174bfff24f9a.png)

How to solve it?

**Comment by e-labInnovations** [comment]
changed `"start": "BROWSER=none PORT=3333 react-scripts start",` in the package.json to `"start": "react-scripts start",`

**Comment by benwinding** [comment]
Glad you got it solved, I forgot stating environment variables like that, is not cross-platform.
