### ISSUE TITLE
error npm start

### ISSUE THREAD

**Issue by andresbelt** [benwinding/react-admin-firebase-demo#12]
Hello, I have this error when try to compile npm start

./src/layouts/DashboardLayout/index.js
Attempted import error: 'Outlet' is not exported from 'react-router-dom'.

thanks in advance

**Comment by benwinding** [comment]
Hey @andresbelt, 
This file doesn't seem to exist in the project: `./src/layouts/DashboardLayout/index.js`
Anymore details you can give?
