### ISSUE TITLE
Supported firebase features

### ISSUE THREAD

**Issue by RWOverdijk** [benwinding/react-admin-firebase-demo#2]
Hey, awesome work on react-admin-firebase. I've looked through it and it looks promising.

I have to start a project that's pretty much 100% firebase. Before I do, I would like to ask you how much of firebase is supported through react-admin-firebase.

Specifically I am looking for:

- storage
- firestore
- ~authentication (login only, but managing users would be cool too)~ _I just saw this is supported. Neat!_

If something's missing I'd like to contribute to the project (unless my schedule changes and I have to work on something else. You know how it goes).

Thanks again!

**Comment by benwinding** [comment]
Thanks for the feedback @RWOverdijk!

Yes, we have successfully implemented the Firestore data provider (with live updates and caching) and authentication using the Firebase client SDK.

We're still looking at implementing a file input component using firebase storage buckets. The `file-input` that comes with `react-admin` is a REST-based component which uses http, however we are looking at implementing one using the firebase sdk. I will try and do it in the next few weeks, as it's been requested a few times.

But if you'd like to have a go yourself, we'll gladly welcome any contributions and pull requests! :grinning: 

Thanks for checking it out!
Ben

**Comment by RWOverdijk** [comment]
@benwinding Awesome stuff! Someone did it here: https://github.com/aymendhaya/ra-data-firebase-client/blob/master/src/demo/App.js

It looks quite simple actually.

Also, don't forget to add your module to the [aor documentation](https://marmelab.com/react-admin/DataProviders.html) 😄

**Comment by benwinding** [comment]
The file input is implemented now.
