### ISSUE TITLE
Are you using realtime database or cloud storage?

### ISSUE THREAD

**Issue by zhouhao27** [benwinding/react-admin-firebase-demo#4]
Are you using realtime database or cloud storage?

**Comment by benwinding** [comment]
@zhouhao27, it uses cloud storage.

It will upload to the bucket specified in this config object.

![image](https://user-images.githubusercontent.com/11782590/66912834-e323ae00-f05a-11e9-9bdb-da6436193d17.png)

More details here: https://github.com/benwinding/react-admin-firebase

**Comment by zhouhao27** [comment]
Thanks for your reply. I think you misunderstand what I mean. Actually I mean database. Here is my database in firebase:

![store](https://user-images.githubusercontent.com/8099731/66971916-83aeb800-f0c5-11e9-89fe-0a5af83b0c71.jpg)

And my code:

![code](https://user-images.githubusercontent.com/8099731/66971989-afca3900-f0c5-11e9-8983-680dacefbe93.jpg)

But it shows **No results found*** in react-admin site. Any suggestion? Thanks.

**Comment by benwinding** [comment]
Hey mate,

Oh I see now, so you can set the "root Ref" as "/" as you don't need to
specify the entire string like that. Try that and let me know 👍

Cheers,

**Comment by zhouhao27** [comment]
Great, it works. Thank you so much.

Ben Winding <notifications@github.com> 于 2019年10月17日周四 上午11:16写道：

> Hey mate,
>
> Oh I see now, so you can set the "root Ref" as "/" as you don't need to
> specify the entire string like that. Try that and let me know 👍
>
> Cheers,
>
>
